=== jredd/demo/book_information.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="book_list" type="book_list_type" />
    <!--<xsd:element name="book">-->
        <xsd:complexType mixed="true" name="book_type">
            <!--<xsd:attribute name="image" type="xsd:anyURI"/>-->
            <!--<xsd:attribute type="xsd:string" name="image"/>-->
            <xsd:sequence>
                <xsd:element name="title" type="capital_first_character_per_word"/>
                <xsd:element name="author" type="author_information"/>
                <xsd:element name="ISBN">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[A-Za-z0-9]{0,3}-[A-Za-z0-9]{0,3}-[A-Za-z0-9]{0,4}"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="price">
                    <xsd:complexType>
                        <xsd:simpleContent>
                            <xsd:extension base="xsd:decimal">
                                <xsd:attribute name="currency">
                                    <xsd:simpleType>
                                        <xsd:restriction base="xsd:string">
                                            <xsd:enumeration value="dollars" />
                                            <xsd:enumeration value="pounds" />
                                            <xsd:enumeration value="euros" />
                                        </xsd:restriction>
                                    </xsd:simpleType>
                                </xsd:attribute>
                            </xsd:extension>
                        </xsd:simpleContent>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="publication_date" type="xsd:date"/>
                <xsd:element name="publisher_information">
                    <xsd:complexType mixed="true">
                        <xsd:sequence>
                            <xsd:element name="publisher" type="capital_first_character_per_word"/>
                            <xsd:element name="address">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="street">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="[0-9]+\s([A-Z][a-zA-Z]*\s*)+"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="suit" type="xsd:positiveInteger" minOccurs="0" />
                                        <xsd:element name="city" type="capital_first_character_per_word" />
                                        <xsd:element name="zip" type="xsd:positiveInteger"/>
                                        <xsd:element name="country">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="[A-Z]+"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="circulation_time" type="xsd:duration" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="image" type="xsd:anyURI"/>
        </xsd:complexType>
    <!--</xsd:element>-->

    <xsd:complexType mixed="true" name="author_information">
        <xsd:sequence>
            <xsd:element name="author_name">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="first" type="capital_first_letter" />
                        <xsd:element name="last" type="capital_first_letter" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="date_of_birth">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:date">
                        <xsd:minInclusive value="1925-01-01"/>
                        <xsd:maxInclusive value="2000-12-31"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="education_level">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="BA" />
                        <xsd:enumeration value="BS" />
                        <xsd:enumeration value="MS" />
                        <xsd:enumeration value="PHD" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Address">
                <xsd:complexType mixed="true">
                    <xsd:sequence>
                        <xsd:element name="street">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="[0-9]+\s([A-Z][a-zA-Z]*\s*)+"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="apt_number" type="xsd:int" minOccurs="0"/>
                        <xsd:element name="city" type="capital_first_character_per_word" />
                        <xsd:element name="zip" type="xsd:positiveInteger"/>
                        <xsd:element name="country">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="[A-Z]+"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="published_count">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="co_authors" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="capital_first_letter">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][a-z]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="capital_first_character_per_word">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z][a-zA-Z]*\s*)+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="book_list_type">
        <xsd:sequence>
            <xsd:element type="book_type" name="book" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== jredd/demo/book_information.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<book_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="book_information.xsd">
  <!--BOOK ONE-->
  <book>
    <title>Sword Of Shannara</title>
    <author>
      <author_name>
        <first>Terry</first>
        <last>Brooks</last>
      </author_name>
      <date_of_birth>1944-01-01</date_of_birth>
      <education_level>BA</education_level>
      <Address>
        <street>3452 North Winchester</street>
        <city>Seattle</city>
        <zip>4354</zip>
        <country>USA</country>
      </Address>
      <published_count>26</published_count>
    </author>
    <ISBN>034-531-4255</ISBN>
    <price currency="dollars">5.98</price>
    <publication_date>2000-10-06</publication_date>
    <publisher_information>
      <publisher>Del Rey</publisher>
      <address>
        <street>1745 Broadway</street>
        <!--Optional:-->
        <suit>201</suit>
        <city>New York</city>
        <zip>10019</zip>
        <country>USA</country>
      </address>
      <circulation_time>P3M5DT50M6S</circulation_time>
    </publisher_information>
  </book><!--ENd BOOK ONE-->

  <book><!--BOOK TWO-->
    <title>Harry Potter And The Half Blood Prince</title>
    <author>
      <author_name>
        <first>Joanne</first>
        <last>Rowling</last>
      </author_name>
      <date_of_birth>1965-08-31</date_of_birth>
      <education_level>BA</education_level>
      <Address>
        <street>19 Hazelbank Terrace</street>
        <city>Edinburgh</city>
        <zip>4354</zip>
        <country>UK</country>
      </Address>
      <published_count>13</published_count>
    </author>
    <ISBN>074-758-1088</ISBN>
    <price currency="dollars">7.86</price>
    <publication_date>2000-10-06</publication_date>
    <publisher_information>
      <publisher>Scholastic Paperbacks</publisher>
      <address>
        <street>2270 Springlake Road</street>
        <!--Optional:-->
        <suit>600</suit>
        <city>Farmers Branch</city>
        <zip>75234</zip>
        <country>USA</country>
      </address>
      <circulation_time>P3M5DT50M6S</circulation_time>
    </publisher_information>
  </book><!--END BOOK TWO-->

  <book><!--BOOK THREE-->
    <title>Clean Code A Handbook Of Agile Software Craftsmanship</title>
    <author>
      <author_name>
        <first>Robert</first>
        <last>Martin</last>
      </author_name>
      <date_of_birth>1952-01-01</date_of_birth>
      <education_level>MS</education_level>
      <Address>
        <street>401 Dont Know</street>
        <city>Dallas</city>
        <zip>7403</zip>
        <country>USA</country>
      </Address>
      <published_count>7</published_count>
    </author>
    <ISBN>013-235-0882</ISBN>
    <price currency="dollars">38.43</price>
    <publication_date>2008-08-11</publication_date>
    <publisher_information>
      <publisher>Prentice Hall</publisher>
      <address>
        <street>1 Lake Street</street>
        <city>Upper Saddle River</city>
        <zip>07458</zip>
        <country>USA</country>
      </address>
      <circulation_time>P3M5DT50M6S</circulation_time>
    </publisher_information>
  </book><!--END BOOK THREE-->

  <book><!--BOOK Four-->
    <title>Harry Potter And The Deathly Hollows</title>
    <author>
      <author_name>
        <first>Joanne</first>
        <last>Rowling</last>
      </author_name>
      <date_of_birth>1965-08-31</date_of_birth>
      <education_level>BA</education_level>
      <Address>
        <street>19 Hazelbank Terrace</street>
        <city>Edinburgh</city>
        <zip>4354</zip>
        <country>UK</country>
      </Address>
      <published_count>13</published_count>
    </author>
    <ISBN>B00-8FN-LM9W</ISBN>
    <price currency="dollars">22.46</price>
    <publication_date>2012-03-27</publication_date>
    <publisher_information>
      <publisher>Pottermore Limited</publisher>
      <address>
        <street>2270 Made Up Road</street>
        <!--Optional:-->
        <city>Somwhere Under</city>
        <zip>75234</zip>
        <country>UK</country>
      </address>
      <circulation_time>P3M5DT50M6S</circulation_time>
    </publisher_information>
  </book><!--END BOOK Four-->
</book_list>
